version: '3'
services:
  backend:
    image: 'dbwjd090/ddang-spring:v1'
    container_name: 'ddang-spring'
    ports:
      - '8080:8080'

  frontend:
    image: 'dbwjd090/ddang-react:v1'
    container_name: 'ddang-react'
    ports:
      - '3000:3000'
    depends_on:
      - backend
